In [1]:
import numpy as np

In [2]:
# Задача 1

n = int(input('Введите число n: '))
np.arange(n, -1, -1)

Введите число n: 5


array([5, 4, 3, 2, 1, 0])

In [8]:
# Задача 2

q = int(input('Введите число q: '))
matr = np.diag(np.arange(q, -1, -1), k=0)
print(matr)
print(sum(sum(matr)))

Введите число q: 5
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
15


In [3]:
# Задача 3

a = np.array ( [ [ 4, 2, 1 ], [ 1, 3, 0 ], [0, 5, 4 ] ] )
b = np.array ( [ 4, 12, -3 ] )
from numpy import linalg
print ( linalg.solve( a, b ) )

[ 0.46666667  3.84444444 -5.55555556]
