In [ ]:
# УРОВЕНЬ 0

In [1]:
import numpy as np

In [3]:
A = np.array( [
    [ 1 ,2, 3],
    [ 4, 5, 6],
    [ 7, 8, 9] ] )
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
C = np.eye(3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
S = A + C
S

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [16]:
V = np.array( [ 1, 2, 3 ] )
V

array([1, 2, 3])

In [20]:
pro = S @ V
pro

array([15., 34., 53.])

In [22]:
S_ = np.linalg.inv(S)
S_

array([[-6. , -2. ,  3. ],
       [-1. ,  0.5,  0. ],
       [ 5. ,  1. , -2. ]])

In [23]:
S @ S_

array([[ 1.00000000e+00, -4.44089210e-16,  8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.77635684e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])