In [1]:
import numpy as np

In [27]:
a = np.array([[-1, 0 , 0],
            [0, -1, 0],
            [0, 0, -1]])
print('Ортогональная диагональная матрица а: \n', a)
a_ = a.transpose()
print('Ее транспонированная матрица: \n', a_)
pro = a @ a_
print('Проверка ортогональности: \n', pro)

Ортогональная диагональная матрица а: 
 [[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Ее транспонированная матрица: 
 [[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Проверка ортогональности: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [37]:
vt = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 1]]) # Единичная матрица является одновременно нижнетреугольной и верхнетреугольной.

vtt = vt.transpose()
print (vtt)
vt @ vtt

[[1 0 0]
 [0 1 0]
 [0 0 1]]


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
d = np. array([[1, 1, 1],
               [1, 2, 1],
               [1, 1, 2]])
print('Матрица, определитель которой равен 1: \n', d)
det = np.linalg.det(d)
print('Определить матрицы: ', det)

Матрица, определитель которой равен 1: 
 [[1 1 1]
 [1 2 1]
 [1 1 2]]
Определить матрицы:  1.0


In [43]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

# Характеристическое уравнение: q^2 - 5q + 4 = 0, корни которого: 4 и 1 (т.е. собственные значения)

# при q = 4: -2x + 2y = 0; x - y = 0
# при q = 1: x + 2y = 0, нет решений.

v = ([[1], 
      [1]])  # Собственный вектор
m @ v

[[2 2]
 [1 3]]


array([[4],
       [4]])